### ISSUE TITLE
detailed readme

### ISSUE THREAD

**Issue by nhjiejan** [AlexsJones/kubernetes-nifi-cluster#1]
could you please put together a detailed readme on how to get this up and running from scratch? im not certain how this project has to work with your zookeeper project and vortex. thanks!

**Comment by AlexsJones** [comment]
Yep I will do @nhjiejan

**Comment by AlexsJones** [comment]
Let me know if the updated readme is detalied enough :) 

P.S - I have a secure cluster repo coming out soon (for https)

**Comment by nhjiejan** [comment]
Awesome stuff. I eventually got it working. Realised I had to tweak it a bit because I was working with kubernetes 1.6. And I had to hack around with the /etc/hosts file on each pod to get the nodes to talk to each other.

I've made a start on a helm repo for nifi. Will let you know when I've posted it up

**Comment by AlexsJones** [comment]
Nice one @nhjiejan considering this closed :+1:
