### ISSUE TITLE
Unable to persisit NIFI data

### ISSUE THREAD

**Issue by arthuersundar** [AlexsJones/kubernetes-nifi-cluster#11]
Hi Alex, New changes are working fine. I tested it. But When the kuberenetes-nifi pods gets restarted, all the data is getting lost. I tried to mount a persistent volume to save the config and start the nifi , but it is not mounting the volume. can you please suggest.

**Comment by AlexsJones** [comment]
Apologies for the super late reply, I will look at this. 
I suspect from what you are saying its probably something in the volume mounts.

**Comment by AlexsJones** [comment]
Closing as it's stale
