### ISSUE TITLE
nifi-zookeeper

### ISSUE THREAD

**Issue by bhargavb7** [AlexsJones/kubernetes-nifi-cluster#3]
nifi.zookeeper.connect.string=zk-0.zk-hs.zookeeper.svc.cluster.local:2181,zk-1.zk-hs.zookeeper.svc.cluster.local:2181

This is the configuration given in the image but in zookeeper for service zk-hs ports 2888 and 3888 are provided and for service zk-cs ports 2181 is provided but in nifi.properties in the above statement the dns is accessing zk-hs service and port 2181

**Comment by AlexsJones** [comment]
Let me double check everything @bhargavb7 
I've actually updated the repo's fairly frequently so I might have some outdated advice. Sorry and I'll get anything wrong corrected.

**Comment by AlexsJones** [comment]
This is 100% my fault and fixed the namespace was wrong
