### ISSUE TITLE
Different version of nifi

### ISSUE THREAD

**Issue by mjschmidt** [AlexsJones/kubernetes-nifi-cluster#4]
Do I need to use xemuliam/nifi:1.4.0?

Would using the base apache nifi image or an alpine distribution work?

Any plans to go to nifi 1.5.0 or 1.6.0?

**Comment by mjschmidt** [comment]
We run in an offline environment, which is why I ask the distribution question

**Comment by mjschmidt** [comment]
This does in fact work with the latest version of nifi. We just had to also install the lookup tool so that we could start getting container pod ips. So we are basically at where you are at with making sure we populated the /etc/hosts file properly.

This should be doable, but we are still figuring out the solution.

**Comment by AlexsJones** [comment]
Thank you for this, there have been a few modifications and I hope to eventually remove the horrible etc/hosts hack completely maybe in favour of a svc/endpoint!

**Comment by mjschmidt** [comment]
Oh, well this is a nice surprise. I will try it out and let you know!
