### ISSUE TITLE
NiFi UI is not reachable after Kube-NiFi-Cluster installed

### ISSUE THREAD

**Issue by abraham0477** [AlexsJones/kubernetes-nifi-cluster#5]
Hi @AlexsJones I have a docker edge single node cluster installed on my mac and I've successfully configured NiFi&ZooKeeper to be run in Kubernetes as followed the repos you have for Kubernetes-nifi-cluster.

My issue here is I need to access the NiFi dashboard? When I ran "docker image or container ls" I don't see anything relate to NiFi? Am I missing something?

Do I need to create a separate docker image preconfigured with its docker file for the product that I'm prototyping before working configuring NiFi cluster with Kube (repo above)? 

Thanks in advance for any further feedback.

**Comment by AlexsJones** [comment]
Every nifi node can serve it's own dashboard.
Can you ensure you can see port 8080 service exposed? 

I suggest trying `kubectl port-forward YOURPODID 8080:8080 -n nifi` then checking in your browser

**Comment by AlexsJones** [comment]
Closing this off
