### ISSUE TITLE
pod has unbound PersistentVolumeClaims

### ISSUE THREAD

**Issue by abraham0477** [AlexsJones/kubernetes-nifi-cluster#6]
Hi,

I'm creating a statefulset resource as following to deploy NiFi statefulset, the resource is successfully configured but when I check the status of the pods they all says pending! 

When I check the status of each pod, it says the pod has unbound PersistentVolumeClaim although I see the volumeClaimTemplates has already included in the statefulset yaml file.

Any idea why I'm seeing this error? I haven't changed anything in the statefulset yaml file and I keep receiving the same error! Shall I need to change something in this yaml file (this has downloaded from this repo).

------------------------
Command1: kubectl apply -f statefulset.yaml 
statefulset.apps "nifi" configured

Command2: kubectl get pods --namespace=nifi
NAME      READY     STATUS    RESTARTS   AGE
nifi-0    0/1       Pending   0          20m
nifi-1    0/1       Pending   0          20m
nifi-2    0/1       Pending   0          20m

Command3: kubectl describe pod nifi-0 --namespace=nifi
Name:           nifi-0
Namespace:      nifi
Node:           <none>
Labels:         app=nifi
                controller-revision-hash=nifi-6cb77fd664
                statefulset.kubernetes.io/pod-name=nifi-0
Annotations:    <none>
Status:         Pending
IP:             
Controlled By:  StatefulSet/nifi
Containers:
  nifi:
    Image:       xemuliam/nifi:1.4.0
    Ports:       8080/TCP, 8081/TCP, 8443/TCP, 2882/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /bin/sh
      -c
    Args:
      chmod +x /opt/nifi/run.sh; cd /opt/nifi && ./run.sh
    Environment:
      ZK_NODES_LIST:    zk-0.zk-hs.zookeeper.svc.cluster.local,zk-1.zk-hs.zookeeper.svc.cluster.local,zk-2.zk-hs.zookeeper.svc.cluster.local
      ZK_MONITOR_PORT:  2888
      IS_CLUSTER_NODE:  yes
      BANNER_TEXT:      Nifi Cluster
    Mounts:
      /opt/nifi/content_repository from contentrepository (rw)
      /opt/nifi/database_repository from databaserepository (rw)
      /opt/nifi/flowfile_repository from flowfilerepository (rw)
      /opt/nifi/provenance_repository from provenancerepository (rw)
      /opt/nifi/run.sh from runconfig (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qqvtt (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  databaserepository:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  databaserepository-nifi-0
    ReadOnly:   false
  contentrepository:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  contentrepository-nifi-0
    ReadOnly:   false
  provenancerepository:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  provenancerepository-nifi-0
    ReadOnly:   false
  flowfilerepository:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  flowfilerepository-nifi-0
    ReadOnly:   false
  runconfig:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      nifi-bootstrap
    Optional:  false
  default-token-qqvtt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-qqvtt
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  37s (x72 over 21m)  default-scheduler  pod has unbound PersistentVolumeClaims

**Comment by AlexsJones** [comment]
More often than not this is due to GCP quota, can you please check this?

**Comment by abraham0477** [comment]
Thanks Alex.

**Comment by abraham0477** [comment]
Further testing requires to be implement on this issue.
