### ISSUE TITLE
/opt/nifi/run.sh: Read-only file system

### ISSUE THREAD

**Issue by arthuersundar** [AlexsJones/kubernetes-nifi-cluster#8]
Hi,
I deployed the NIFI in our kubernetes cluster. PODs are getting crashed. Getting "Read-only file system "error.

I have mounted the PVC in RWO mode. Please advise.

sh-4.2# kubectl logs nifi-2 -n nifi
chmod: /opt/nifi/run.sh: Read-only file system
/bin/sh: ./run.sh: Permission denied
sh-4.2#

sh-4.2# kubectl get pvc -n nifi
NAME                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
contentrepository-nifi-0      Bound     pvc-46732074-353c-11e9-92cb-52bc1c68b7eb   5Gi        RWO            default        8s
contentrepository-nifi-1      Bound     pvc-4694d649-353c-11e9-92cb-52bc1c68b7eb   5Gi        RWO            default        8s
contentrepository-nifi-2      Bound     pvc-46ab72a3-353c-11e9-92cb-52bc1c68b7eb   5Gi        RWO            default        7s

**Comment by srishti-gajare** [comment]
I had faced a similar issue. Under volumes in nifi.yaml file add defaultMode 0777,  should be good to go with that.

Something like this 

```volumes:
      - name: runconfig
        configMap:
          name: nifi-bootstrap
          defaultMode: 0777

**Comment by arthuersundar** [comment]
Thanks for the suggestion. I will test this out.

Are you able to deploy nifi and zookeeper in kubernetes ?

**Comment by arthuersundar** [comment]
Hi, I tried as per your suggestion. Im getting the below error now.  Are you able to deploy nifi and zookeeper successfully in kubernetes ?

sh-4.2# kubectl logs nifi-0 -n nifi
chmod: changing permissions of '/opt/nifi/run.sh': Read-only file system
Waiting to run nslookup...
./run.sh: 3: ./run.sh: cannot create /tmphosts: Permission denied
./run.sh: 1: ./run.sh: nslookup: not found
sed: can't read /tmphosts: No such file or directory
sed: can't read /tmphosts: No such file or directory
sed: can't read /tmphosts: No such file or directory
sed: can't read /tmphosts: No such file or directory
./run.sh: 8: ./run.sh: cannot create /etc/hosts: Permission denied
./run.sh: 9: ./run.sh: ./start_nifi.sh: not found
sh-4.2#

**Comment by srishti-gajare** [comment]
Yes I am able to run 2 pod nifi cluster with 3 zookeeper pods for nifi cluster coordination.  Also do not add chmod in the command section of yaml instead add the following.

```command: ["/bin/sh","-c","cd /opt/nifi/ && ./run.sh"] ```

**Comment by arthuersundar** [comment]
sh-4.2# cat nifi-bootstrap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nifi-bootstrap
data:
  run.sh: |-
    echo "Waiting to run nslookup..."
    sleep 30
    echo `nslookup nifi | sed -e 's/Address.*://' | tail -n +3` | sed -e 's/l /l\n/g' >>  /tmphosts
    sed -i 's/nifi-0.nifi.nifi.svc.cluster.local/nifi-0.nifi.nifi.svc.cluster.local nifi-0/g' /tmphosts
    sed -i 's/nifi-1.nifi.nifi.svc.cluster.local/nifi-1.nifi.nifi.svc.cluster.local nifi-1/g' /tmphosts
    sed -i 's/nifi-2.nifi.nifi.svc.cluster.local/nifi-2.nifi.nifi.svc.cluster.local nifi-2/g' /tmphosts
    sed -i 's/nifi-3.nifi.nifi.svc.cluster.local/nifi-3.nifi.nifi.svc.cluster.local nifi-3/g' /tmphosts
    cat /tmphosts >> /etc/hosts
    ./start_nifi.sh
sh-4.2#

**Comment by arthuersundar** [comment]
sh-4.2#
sh-4.2# cat statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nifi
spec:
  serviceName: nifi
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nifi
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - nifi
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: nifi
          image: apache/nifi
          command: ["/bin/sh","-c"]
          args: ["chmod +x /opt/nifi/run.sh; cd /opt/nifi && ./run.sh"]
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
            - containerPort: 8443
            - containerPort: 2882
          volumeMounts:
            - name: runconfig
              mountPath: /opt/nifi/run.sh
              subPath: run.sh
            - name: flowfilerepository
              mountPath: /opt/nifi/flowfile_repository
            - name: databaserepository
              mountPath: /opt/nifi/database_repository
            - name: contentrepository
              mountPath: /opt/nifi/content_repository
            - name: provenancerepository
              mountPath: /opt/nifi/provenance_repository
          env:
            - name: ZK_NODES_LIST
              value: "zk-0.zk-hs.zookeeper.svc.cluster.local,zk-1.zk-hs.zookeeper.svc.cluster.local,zk-2.zk-hs.zookeeper.svc.cluster.local"
            - name: ZK_MONITOR_PORT
              value: "2888"
            - name: IS_CLUSTER_NODE
              value: "yes"
            - name: BANNER_TEXT
              value: "Nifi Cluster"
      volumes:
      - name: runconfig
        configMap:
          name: nifi-bootstrap
          defaultMode: 0777
  volumeClaimTemplates:
  - metadata:
      name: flowfilerepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: default
  - metadata:
      name: databaserepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: default
  - metadata:
      name: contentrepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: default
  - metadata:
      name: provenancerepository
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: default
sh-4.2#

**Comment by arthuersundar** [comment]
sh-4.2# cat service.yaml
kind: Service
apiVersion: v1
metadata:
  name: nifi-http
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: nifi

---

kind: Service
apiVersion: v1
metadata:
  name: nifi
spec:
  clusterIP: None
  selector:
    app: nifi
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: nifi-listen-http
    - protocol: TCP
      port: 2881
      targetPort: 2881
      name: nifi-site-protocol
    - protocol: TCP
      port: 2882
      targetPort: 2882
      name: nifi-node-protocol
sh-4.2#
sh-4.2#

**Comment by arthuersundar** [comment]
these are the YAML files i using to deploy the NIFI & Kubernetes

**Comment by arthuersundar** [comment]
can you send me the working config to deploy NIFI and zookeeper in Kubernetes,

**Comment by srishti-gajare** [comment]
Everything looks fine just change the "command section" in statefulset.yaml to whatever I have mentioned above.

**Comment by arthuersundar** [comment]
Getting below error now. If possible can you send me the working config of NIFI and Zookeeper.

sh-4.2#
sh-4.2# kubectl logs nifi-0 -n nifi
Waiting to run nslookup...
./run.sh: 3: ./run.sh: cannot create /tmphosts: Permission denied
./run.sh: 1: ./run.sh: nslookup: not found
sed: can't read /tmphosts: No such file or directory
sed: can't read /tmphosts: No such file or directory
sed: can't read /tmphosts: No such file or directory
sed: can't read /tmphosts: No such file or directory
./run.sh: 8: ./run.sh: cannot create /etc/hosts: Permission denied
./run.sh: 9: ./run.sh: ./start_nifi.sh: not found
sh-4.2#
sh-4.2#

**Comment by arthuersundar** [comment]
im able to start the container now..  any idea on this error

2019-03-05 06:31:07,249 WARN [main] o.a.nifi.controller.StandardFlowService There is currently no Cluster Coordinator. This often happens upon restart of NiFi when running an embedded ZooKeeper. Will register this node to become the active Cluster Coordinator and will attempt to connect to cluster again
2019-03-05 06:31:07,249 INFO [main] o.a.n.c.l.e.CuratorLeaderElectionManager CuratorLeaderElectionManager[stopped=false] Attempted to register Leader Election for role 'Cluster Coordinator' but this role is already registered
2019-03-05 06:31:08,806 ERROR [Leader Election Notification Thread-1] o.a.c.f.imps.CuratorFrameworkImpl Background exception was not retry-able or retry gave up
java.net.UnknownHostException: zk-0.zk-hs.zookeeper.svc.cluster.local
        at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
        at java.net.InetAddress.getAllByName(InetAddress.java:1192)
        at java.net.InetAddress.getAllByName(InetAddress.java:1126)
        at org.apache.zookeeper.client.StaticHostProvider.<init>(StaticHostProvider.java:61)

**Comment by srishti-gajare** [comment]
Nifi pods are unable to connect to zookeeper pods check if you have given the right names for zookeeper.

**Comment by arthuersundar** [comment]
Hi, im able to start the NIFI cluster now. I have problems startign the zookeeper cluster. gettign below error.

sh-4.2# kubectl create -f statefulset.yaml --namespace=zk
error: error parsing statefulset.yaml: error converting YAML to JSON: yaml: line 16: did not find expected node content
sh-4.2#

**Comment by arthuersundar** [comment]
Below are my zookeeper config file. can you please let me know if somethign needs to be changed.

sh-4.2# cat namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: zk
sh-4.2#

sh-4.2# cat service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: zk
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
sh-4.2#
sh-4.2#

sh-4.2# cat poddisruptionbudget.yaml
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: zk
spec:
  selector:
    matchLabels:
      app: zk
  maxUnavailable: 1
sh-4.2#
sh-4.2#


sh-4.2#
sh-4.2# cat statefulset.yaml
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  namespace: zk
  name: zk
spec:
  serviceName: zk-hs
  replicas: {{.servers}}
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zk
    spec:
      {{- if .affinity_key }}
      {{- if .affinity_selector }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: {{.affinity_key}}
                operator: In
                values:
                - {{.affinity_selector}}
      {{- end }}
      {{- end }}
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: {{.image}}
        resources:
          requests:
            memory: {{.memoryrequest}}
            cpu: {{.cpurequest}}
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        command:
        - sh
        - -c
        - "start-zookeeper \
          --servers={{.servers}} \
          --data_dir=/var/lib/zookeeper/data \
          --data_log_dir=/var/lib/zookeeper/data/log \
          --conf_dir=/opt/zookeeper/conf \
          --client_port=2181 \
          --election_port=3888 \
          --server_port=2888 \
          --tick_time=2000 \
          --init_limit=10 \
          --sync_limit=5 \
          --heap={{.heapsize}} \
          --max_client_cnxns=60 \
          --snap_retain_count=3 \
          --purge_interval=12 \
          --max_session_timeout=40000 \
          --min_session_timeout=4000 \
          --log_level=INFO"
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "zookeeper-ready 2181"
          initialDelaySeconds: 10
          timeoutSeconds: 5
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/zookeeper
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{.storagesize}}
sh-4.2#

**Comment by AlexsJones** [comment]
To the original poster:
- Apologies for the delay in response (I really am)
- I have pushed a version that does not require a shell script to be mounted, can you please try pulling latest and trying?

**Comment by AlexsJones** [comment]
This has been resolved as no longer needing hacky files!
