### ISSUE TITLE
Also why vortex rather than helm?

### ISSUE THREAD

**Issue by mjschmidt** [AlexsJones/kubernetes-nifi-cluster#9]
Just curious, this seems to be the best way to engage at the moment (:

**Comment by savardmario** [comment]
I had the same question. What is Vortex? Then understood it was homemade helm.

**Comment by mjschmidt** [comment]
@savardmario its usually for modding games lol

Like I use it for skyrim

**Comment by AlexsJones** [comment]
Yep it's a home made helm, but stripped back to use the golang yaml parser directly without having to use additional syntax. There is *no* requirement to use it at all - you can just annotate your templates directly
